### ISSUE TITLE
Incoming Mail to Database

### ISSUE THREAD

**Issue by dglunz** [CampbellGlunz/circle#10]
http://robots.thoughtbot.com/handle-incoming-email-with-griddler
Email > Griddler route to parse email > store in db

**Comment by Zandrr** [comment]
I did a bit of research, and I think this is the easiest way to do it:

**1) Create new domain using gmail: add@indorse.ly**
- *user sends email from their email client*


**2) Receive emails via [SendGrid Parser API](https://sendgrid.com/blog/sendgrids-parse-api-parsing-incoming-email-is-now-faster-and-easier/)**
- *this will be posted to a specified endpoint*


**3) Using Griddler, we will do some processing (accept JSON on specified endpoint)**
- *add JSON to database based on the email address that was used to send the email to **add@indorse.ly** in the first place* - this will ensure you can only add people you indorse to your own profile.

Let me know what you think/any thoughts on how to improve or change.  Once I we agree on the architecture, I'll get going on coding it.
